from pydantic import BaseModel, EmailStr, ConfigDict, Field, SecretStr, field_serializer
from typing import Annotated
from uuid import UUID
from datetime import datetime
from enum import Enum

from app.model.user import OTPType
from app.schemas.base_response import BaseResponse

class UserBase(BaseModel): 
    first_name: Annotated[str, Field(description="User first name", examples=['John'])]
    last_name: Annotated[str, Field(description="User Last Name", examples=["Doe"])]
    email: Annotated[EmailStr, Field(description="User email", examples=["johndoe@example.com"])]

    
class UserCreate(UserBase):
    password: Annotated[SecretStr, Field(
        description="User password", 
        examples=["johnexample"],
        min_length=8,
        max_length=64
    )]
    
    model_config = ConfigDict(extra="forbid")
    
class UserCreateInternals(UserBase):
    password: Annotated[str, Field(description="User hashed password", examples=["dithd3Ddll...."])]
    otp: Annotated[str, Field(description="Autogenerated otp for email verification", examples=["123456"])]
    otp_expiry: Annotated[datetime, Field(description="OTP expiry time")]
    otp_type: Annotated[OTPType, Field(description="The Type of the Otp", examples=[OTPType.EMAIL_VERIFICATION.value])]
    
    
class UserRead(UserBase):
    is_active: Annotated[bool, Field(description="True if user is active otherwise False", default=True)]
    id: Annotated[UUID, Field(description="User Id", examples=["1234-33ddh-dhdh-33esd-3303"])]
    created_at: Annotated[datetime, Field(description="When user was created", examples=["2026-01-20"])]
    updated_at: Annotated[datetime, Field(description="When User was updated last", examples=["2026-01-23"])]

    
    @field_serializer("id")
    def serialize_id(self, v: UUID) -> str: 
        return str(v)
    
    @field_serializer("created_at", "updated_at")
    def serialize_datetime(self, v: datetime) -> str:
        return v.isoformat()
    
    
class UserUpdate(BaseModel):
    first_name: Annotated[str, Field(description="User first nanem", examples=["John"])]
    last_name: Annotated[str, Field(description="User last name", examples=["Doe"])]

    model_config = ConfigDict(extra="forbid")
    
    
class Userfilter(BaseModel):
    first_name: str | None = None
    last_name: str | None = None
    email: str | None = None
    
class UUIDSchema(BaseModel):
    id: UUID
    
class UserResponse(BaseResponse):
    data: Annotated[UserRead, Field(description="User created data")]