"""remove session_id column from refresh_token table

Revision ID: 3990b4df74d2
Revises: fbe3ed202028
Create Date: 2026-02-05 02:34:28.996469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3990b4df74d2'
down_revision: Union[str, Sequence[str], None] = 'fbe3ed202028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('refresh_tokens_session_id_key'), type_='unique')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('refresh_tokens_session_id_key'), ['session_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
