"""remove unique contraint on device_id in refresh_token table

Revision ID: 685a36f6f512
Revises: 3990b4df74d2
Create Date: 2026-02-07 23:41:58.036712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685a36f6f512'
down_revision: Union[str, Sequence[str], None] = '3990b4df74d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('refresh_tokens_device_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('refresh_tokens_device_id_key'), ['device_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
