"""add forgot password to  otp enum type

Revision ID: daf7a4497374
Revises: e3526261b983
Create Date: 2026-02-12 09:34:03.417678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf7a4497374'
down_revision: Union[str, Sequence[str], None] = 'e3526261b983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE otp_type_enum ADD VALUE IF NOT EXISTS 'FORGOT_PASSWORD'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
