"""add row_count and column_count to dataset table

Revision ID: e3526261b983
Revises: 685a36f6f512
Create Date: 2026-02-09 13:46:07.209538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3526261b983'
down_revision: Union[str, Sequence[str], None] = '685a36f6f512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('column_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('column_count')
        batch_op.drop_column('row_count')

    # ### end Alembic commands ###
